import { 
  BookOpen, 
  Laptop, 
  Shirt, 
  Trophy, 
  Palette, 
  Apple 
} from 'lucide-react'

export interface GalleryImage {
  id: number;
  src: string;
  alt: string;
  category: string;
  title: string;
  description: string;
}

export const categories = [
  { id: 'all', name: 'All' },
  { id: 'events', name: 'Events' },
  { id: 'classes', name: 'Classes' },
  { id: 'workshops', name: 'Workshops' },
  { id: 'achievements', name: 'Achievements' },
]

export const galleryImages: GalleryImage[] = [
        {
          id: 1,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-classroom-1.jpg',
          alt: 'Students in study session',
          category: 'classes',
          title: 'Collaborative Learning',
          description: 'Students working together to solve mathematics problems',
        },
        {
          id: 2,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-hero.jpg',
          alt: 'Science workshop',
          category: 'workshops',
          title: 'Science Workshop',
          description: 'Interactive workshop focusing on science and technology',
        },
        {
          id: 3,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-Outdoor.jpg',
          alt: 'Students in outdoor session',
          category: 'classes',
          title: 'Outdoor Learning',
          description: 'Learning science concepts in a natural environment',
        },
        {
          id: 4,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-learners.jpg',
          alt: 'STEM camp activity',
          category: 'workshops',
          title: 'STEM Camp',
          description: 'Students engaged in STEM activities during holiday camp',
        },
        {
          id: 6,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-talks.jpg',
          alt: 'Educational presentation',
          category: 'events',
          title: 'Educational Talk',
          description: 'Guest speaker sharing knowledge with students',
        },
        {
          id: 7,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-donations.jpg',
          alt: 'Community outreach program',
          category: 'events',
          title: 'Community Support',
          description: 'Distributing educational materials to community members',
        },
        {
          id: 8,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-giftbags.jpg',
          alt: 'School outreach program',
          category: 'events',
          title: 'School Visit',
          description: 'Providing resources to local schools',
        },
        {
          id: 9,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-jongi1.jpg',
          alt: 'School outreach program',
          category: 'events',
          title: 'School Visit',
          description: 'Engaging with students at local schools',
        },
        {
          id: 10,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-jongi2.jpg',
          alt: 'School outreach program',
          category: 'events',
          title: 'School Visit',
          description: 'Supporting education in underserved communities',
        },
        {
          id: 11,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-jongi3.jpg',
          alt: 'School outreach program',
          category: 'events',
          title: 'School Visit',
          description: 'Bringing resources to rural schools',
        },
        {
          id: 12,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-jongi4.jpg',
          alt: 'School outreach program',
          category: 'events',
          title: 'School Visit',
          description: 'Providing educational support to schools',
        },
        {
          id: 13,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-jongi6.jpg',
          alt: 'School outreach program',
          category: 'events',
          title: 'School Visit',
          description: 'Donating educational materials to students',
        },
        {
          id: 14,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-learner.png',
          alt: 'Students in classroom',
          category: 'classes',
          title: 'Mathematics Class',
          description: 'Students learning advanced mathematics concepts',
        },
        {
          id: 15,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-teaching.jpg',
          alt: 'Educator in action',
          category: 'classes',
          title: 'Inspiring Teaching Moment',
          description: 'Teacher explaining complex concepts in an engaging way',
        },
        {
          id: 16,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-classroom-3.jpg',
          alt: 'Student group',
          category: 'classes',
          title: 'Learning Together',
          description: 'Students collaborating on a science project',
        },
        {
          id: 17,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-tutor workshop.png',
          alt: 'Tutor workshop',
          category: 'workshops',
          title: 'Tutor Workshop',
          description: 'Interactive workshop focusing on science and technology',
        },
        {
          id: 18,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-councelling.jpg',
          alt: 'Community event',
          category: 'events',
          title: 'Community Day',
          description: 'Engaging with the local community through educational activities',
        },
        {
          id: 19,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-mobile-laboratories.jpg',
          alt: 'Science laboratory session',
          category: 'workshops',
          title: 'Science Lab',
          description: 'Hands-on experiments in our mobile science laboratory',
        },
        {
          id: 20,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-tutor.jpg',
          alt: 'One-on-one tutoring',
          category: 'classes',
          title: 'Individual Tutoring',
          description: 'Personalized learning support for students',
        },
        {
          id: 21,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-shawburry1.jpg',
          alt: 'Educational presentation',
          category: 'events',
          title: 'Educational Talk',
          description: 'Sharing knowledge and inspiration with students',
        },
        {
          id: 22,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-shawburry2.jpg',
          alt: 'Educational presentation',
          category: 'events',
          title: 'Educational Talk',
          description: 'Guest speaker engaging with students',
        },
        {
          id: 23,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-shawburry3.jpg',
          alt: 'Educational presentation',
          category: 'events',
          title: 'Educational Talk',
          description: 'Interactive presentation on STEM topics',
        },
        {
          id: 24,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-shawburry4.jpg',
          alt: 'Educational presentation',
          category: 'events',
          title: 'Educational Talk',
          description: 'Students engaged in a knowledge-sharing session',
        },
        {
          id: 25,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-tutor-development.jpg',
          alt: 'Tutor development session',
          category: 'workshops',
          title: 'Tutor Development Workshop',
          description: 'Training and upskilling our tutors for better education delivery',
        },
        {
          id: 26,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-classroom-2.jpg',
          alt: 'Students in study session',
          category: 'classes',
          title: 'Collaborative Learning',
          description: 'Students working together on challenging academic problems',
        },
        {
          id: 27,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-application.jpg',
          alt: 'Student application process',
          category: 'classes',
          title: 'Application Process',
          description: 'Students getting assistance with program applications',
        },
        {
          id: 28,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-application-2.jpg',
          alt: 'Student application session',
          category: 'classes',
          title: 'Application Support',
          description: 'Providing guidance during the application process',
        },
        {
          id: 29,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-application-3.jpg',
          alt: 'Application workshop',
          category: 'workshops',
          title: 'Application Workshop',
          description: 'Group session for helping students with applications',
        },
        {
          id: 30,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-application-4.jpg',
          alt: 'Application assistance',
          category: 'classes',
          title: 'One-on-One Application Help',
          description: 'Personalized assistance with program applications',
        },
        {
          id: 31,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-classroom-learners.jpg',
          alt: 'Classroom learning',
          category: 'classes',
          title: 'Engaged Learning',
          description: 'Students actively participating in classroom activities',
        },
        {
          id: 32,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-header.jpg',
          alt: 'Program overview',
          category: 'events',
          title: 'MSI Program',
          description: 'Showcasing our comprehensive educational initiatives',
        },
        {
          id: 33,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-lab.jpg',
          alt: 'Laboratory session',
          category: 'workshops',
          title: 'Science Laboratory',
          description: 'Students conducting experiments in our science lab',
        },
        {
          id: 34,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-lab-1.jpg',
          alt: 'Science experiment',
          category: 'workshops',
          title: 'Hands-on Science',
          description: 'Practical laboratory experience for students',
        },
        {
          id: 35,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-learners-alphendale.jpg',
          alt: 'Alphendale students',
          category: 'classes',
          title: 'Alphendale Learning Center',
          description: 'Students at our Alphendale educational facility',
        },
        {
          id: 36,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-learner-development.JPG',
          alt: 'Learner Development',
          category: 'classes',
          title: 'Learner Development',
          description: 'Students engaged in educational activities',
        },
        {
          id: 37,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-outdoor-work.jpg',
          alt: 'Outdoor activities',
          category: 'workshops',
          title: 'Field Work',
          description: 'Learning through practical outdoor activities',
        },
        {
          id: 38,
          src: 'https://d1dc40k4xbphr.cloudfront.net/images/gallery/msi-staff.jpg',
          alt: 'MSI staff members',
          category: 'events',
          title: 'Our Team',
          description: 'Dedicated educators and staff working to support student success',
        }
]